"""feat: nova propriedade de Imoveis (esta_em_destaque)

Revision ID: 7c76b957d1c6
Revises: 
Create Date: 2026-03-27 19:21:31.670284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c76b957d1c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plantas_imovel')
    with op.batch_alter_table('imoveis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('esta_em_destaque', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imoveis', schema=None) as batch_op:
        batch_op.drop_column('esta_em_destaque')

    op.create_table('plantas_imovel',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('imovel_id', sa.INTEGER(), nullable=False),
    sa.Column('caminho_da_imagem_da_planta1', sa.VARCHAR(length=100), nullable=True),
    sa.Column('descricao_da_planta1', sa.VARCHAR(length=500), nullable=True),
    sa.Column('caminho_da_imagem_da_planta2', sa.VARCHAR(length=100), nullable=True),
    sa.Column('descricao_da_planta2', sa.VARCHAR(length=500), nullable=True),
    sa.Column('caminho_da_imagem_da_planta3', sa.VARCHAR(length=100), nullable=True),
    sa.Column('descricao_da_planta3', sa.VARCHAR(length=500), nullable=True),
    sa.Column('caminho_da_imagem_da_planta4', sa.VARCHAR(length=100), nullable=True),
    sa.Column('descricao_da_planta4', sa.VARCHAR(length=500), nullable=True),
    sa.Column('caminho_da_imagem_da_planta5', sa.VARCHAR(length=100), nullable=True),
    sa.Column('descricao_da_planta5', sa.VARCHAR(length=500), nullable=True),
    sa.Column('caminho_da_imagem_da_planta6', sa.VARCHAR(length=100), nullable=True),
    sa.Column('descricao_da_planta6', sa.VARCHAR(length=500), nullable=True),
    sa.Column('caminho_da_imagem_da_planta7', sa.VARCHAR(length=100), nullable=True),
    sa.Column('descricao_da_planta7', sa.VARCHAR(length=500), nullable=True),
    sa.Column('caminho_da_imagem_da_planta8', sa.VARCHAR(length=100), nullable=True),
    sa.Column('descricao_da_planta8', sa.VARCHAR(length=500), nullable=True),
    sa.Column('caminho_da_imagem_da_planta9', sa.VARCHAR(length=100), nullable=True),
    sa.Column('descricao_da_planta9', sa.VARCHAR(length=500), nullable=True),
    sa.Column('caminho_da_imagem_da_planta10', sa.VARCHAR(length=100), nullable=True),
    sa.Column('descricao_da_planta10', sa.VARCHAR(length=500), nullable=True),
    sa.ForeignKeyConstraint(['imovel_id'], ['imoveis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
