"""feat: slug que será utilizado para pesquisas por nome ao invés de id

Revision ID: abae2f1d6e18
Revises: 7c76b957d1c6
Create Date: 2026-03-29 10:52:09.214832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abae2f1d6e18'
down_revision = '7c76b957d1c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imoveis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imoveis', schema=None) as batch_op:
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
